/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MinhaContaRouteImport } from './routes/minha-conta'
import { Route as MeusPedidosRouteImport } from './routes/meus-pedidos'
import { Route as DriverRouteImport } from './routes/driver'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CardapioRouteImport } from './routes/cardapio'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PedidoIdRouteImport } from './routes/pedido.$id'
import { Route as DriverProfileRouteImport } from './routes/driver.profile'
import { Route as DriverPerformanceRouteImport } from './routes/driver.performance'
import { Route as DriverJornadaRouteImport } from './routes/driver.jornada'
import { Route as DriverEarningsRouteImport } from './routes/driver.earnings'
import { Route as DriverDashboardRouteImport } from './routes/driver.dashboard'
import { Route as DriverAchievementsRouteImport } from './routes/driver.achievements'
import { Route as AdminPagamentoRouteImport } from './routes/admin/pagamento'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminEntregasRouteImport } from './routes/admin/entregas'
import { Route as AdminEntregasRelatoriosRouteImport } from './routes/admin/entregas.relatorios'
import { Route as AdminEntregasPedidosRouteImport } from './routes/admin/entregas.pedidos'
import { Route as AdminEntregadoresMapaRouteImport } from './routes/admin/entregadores.mapa'
import { Route as AdminEntregadoresAcessosRouteImport } from './routes/admin/entregadores.acessos'

const MinhaContaRoute = MinhaContaRouteImport.update({
  id: '/minha-conta',
  path: '/minha-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const MeusPedidosRoute = MeusPedidosRouteImport.update({
  id: '/meus-pedidos',
  path: '/meus-pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRoute = DriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CardapioRoute = CardapioRouteImport.update({
  id: '/cardapio',
  path: '/cardapio',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PedidoIdRoute = PedidoIdRouteImport.update({
  id: '/pedido/$id',
  path: '/pedido/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverProfileRoute = DriverProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DriverRoute,
} as any)
const DriverPerformanceRoute = DriverPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => DriverRoute,
} as any)
const DriverJornadaRoute = DriverJornadaRouteImport.update({
  id: '/jornada',
  path: '/jornada',
  getParentRoute: () => DriverRoute,
} as any)
const DriverEarningsRoute = DriverEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => DriverRoute,
} as any)
const DriverDashboardRoute = DriverDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DriverRoute,
} as any)
const DriverAchievementsRoute = DriverAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => DriverRoute,
} as any)
const AdminPagamentoRoute = AdminPagamentoRouteImport.update({
  id: '/pagamento',
  path: '/pagamento',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEntregasRoute = AdminEntregasRouteImport.update({
  id: '/entregas',
  path: '/entregas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEntregasRelatoriosRoute = AdminEntregasRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AdminEntregasRoute,
} as any)
const AdminEntregasPedidosRoute = AdminEntregasPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AdminEntregasRoute,
} as any)
const AdminEntregadoresMapaRoute = AdminEntregadoresMapaRouteImport.update({
  id: '/entregadores/mapa',
  path: '/entregadores/mapa',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEntregadoresAcessosRoute =
  AdminEntregadoresAcessosRouteImport.update({
    id: '/entregadores/acessos',
    path: '/entregadores/acessos',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cardapio': typeof CardapioRoute
  '/checkout': typeof CheckoutRoute
  '/driver': typeof DriverRouteWithChildren
  '/meus-pedidos': typeof MeusPedidosRoute
  '/minha-conta': typeof MinhaContaRoute
  '/admin/entregas': typeof AdminEntregasRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/pagamento': typeof AdminPagamentoRoute
  '/driver/achievements': typeof DriverAchievementsRoute
  '/driver/dashboard': typeof DriverDashboardRoute
  '/driver/earnings': typeof DriverEarningsRoute
  '/driver/jornada': typeof DriverJornadaRoute
  '/driver/performance': typeof DriverPerformanceRoute
  '/driver/profile': typeof DriverProfileRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/entregadores/acessos': typeof AdminEntregadoresAcessosRoute
  '/admin/entregadores/mapa': typeof AdminEntregadoresMapaRoute
  '/admin/entregas/pedidos': typeof AdminEntregasPedidosRoute
  '/admin/entregas/relatorios': typeof AdminEntregasRelatoriosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cardapio': typeof CardapioRoute
  '/checkout': typeof CheckoutRoute
  '/driver': typeof DriverRouteWithChildren
  '/meus-pedidos': typeof MeusPedidosRoute
  '/minha-conta': typeof MinhaContaRoute
  '/admin/entregas': typeof AdminEntregasRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/pagamento': typeof AdminPagamentoRoute
  '/driver/achievements': typeof DriverAchievementsRoute
  '/driver/dashboard': typeof DriverDashboardRoute
  '/driver/earnings': typeof DriverEarningsRoute
  '/driver/jornada': typeof DriverJornadaRoute
  '/driver/performance': typeof DriverPerformanceRoute
  '/driver/profile': typeof DriverProfileRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/entregadores/acessos': typeof AdminEntregadoresAcessosRoute
  '/admin/entregadores/mapa': typeof AdminEntregadoresMapaRoute
  '/admin/entregas/pedidos': typeof AdminEntregasPedidosRoute
  '/admin/entregas/relatorios': typeof AdminEntregasRelatoriosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cardapio': typeof CardapioRoute
  '/checkout': typeof CheckoutRoute
  '/driver': typeof DriverRouteWithChildren
  '/meus-pedidos': typeof MeusPedidosRoute
  '/minha-conta': typeof MinhaContaRoute
  '/admin/entregas': typeof AdminEntregasRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/pagamento': typeof AdminPagamentoRoute
  '/driver/achievements': typeof DriverAchievementsRoute
  '/driver/dashboard': typeof DriverDashboardRoute
  '/driver/earnings': typeof DriverEarningsRoute
  '/driver/jornada': typeof DriverJornadaRoute
  '/driver/performance': typeof DriverPerformanceRoute
  '/driver/profile': typeof DriverProfileRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/entregadores/acessos': typeof AdminEntregadoresAcessosRoute
  '/admin/entregadores/mapa': typeof AdminEntregadoresMapaRoute
  '/admin/entregas/pedidos': typeof AdminEntregasPedidosRoute
  '/admin/entregas/relatorios': typeof AdminEntregasRelatoriosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cardapio'
    | '/checkout'
    | '/driver'
    | '/meus-pedidos'
    | '/minha-conta'
    | '/admin/entregas'
    | '/admin/login'
    | '/admin/pagamento'
    | '/driver/achievements'
    | '/driver/dashboard'
    | '/driver/earnings'
    | '/driver/jornada'
    | '/driver/performance'
    | '/driver/profile'
    | '/pedido/$id'
    | '/admin/'
    | '/admin/entregadores/acessos'
    | '/admin/entregadores/mapa'
    | '/admin/entregas/pedidos'
    | '/admin/entregas/relatorios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cardapio'
    | '/checkout'
    | '/driver'
    | '/meus-pedidos'
    | '/minha-conta'
    | '/admin/entregas'
    | '/admin/login'
    | '/admin/pagamento'
    | '/driver/achievements'
    | '/driver/dashboard'
    | '/driver/earnings'
    | '/driver/jornada'
    | '/driver/performance'
    | '/driver/profile'
    | '/pedido/$id'
    | '/admin'
    | '/admin/entregadores/acessos'
    | '/admin/entregadores/mapa'
    | '/admin/entregas/pedidos'
    | '/admin/entregas/relatorios'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cardapio'
    | '/checkout'
    | '/driver'
    | '/meus-pedidos'
    | '/minha-conta'
    | '/admin/entregas'
    | '/admin/login'
    | '/admin/pagamento'
    | '/driver/achievements'
    | '/driver/dashboard'
    | '/driver/earnings'
    | '/driver/jornada'
    | '/driver/performance'
    | '/driver/profile'
    | '/pedido/$id'
    | '/admin/'
    | '/admin/entregadores/acessos'
    | '/admin/entregadores/mapa'
    | '/admin/entregas/pedidos'
    | '/admin/entregas/relatorios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CardapioRoute: typeof CardapioRoute
  CheckoutRoute: typeof CheckoutRoute
  DriverRoute: typeof DriverRouteWithChildren
  MeusPedidosRoute: typeof MeusPedidosRoute
  MinhaContaRoute: typeof MinhaContaRoute
  PedidoIdRoute: typeof PedidoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/minha-conta': {
      id: '/minha-conta'
      path: '/minha-conta'
      fullPath: '/minha-conta'
      preLoaderRoute: typeof MinhaContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meus-pedidos': {
      id: '/meus-pedidos'
      path: '/meus-pedidos'
      fullPath: '/meus-pedidos'
      preLoaderRoute: typeof MeusPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver': {
      id: '/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof DriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cardapio': {
      id: '/cardapio'
      path: '/cardapio'
      fullPath: '/cardapio'
      preLoaderRoute: typeof CardapioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/pedido/$id': {
      id: '/pedido/$id'
      path: '/pedido/$id'
      fullPath: '/pedido/$id'
      preLoaderRoute: typeof PedidoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/profile': {
      id: '/driver/profile'
      path: '/profile'
      fullPath: '/driver/profile'
      preLoaderRoute: typeof DriverProfileRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/performance': {
      id: '/driver/performance'
      path: '/performance'
      fullPath: '/driver/performance'
      preLoaderRoute: typeof DriverPerformanceRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/jornada': {
      id: '/driver/jornada'
      path: '/jornada'
      fullPath: '/driver/jornada'
      preLoaderRoute: typeof DriverJornadaRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/earnings': {
      id: '/driver/earnings'
      path: '/earnings'
      fullPath: '/driver/earnings'
      preLoaderRoute: typeof DriverEarningsRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/dashboard': {
      id: '/driver/dashboard'
      path: '/dashboard'
      fullPath: '/driver/dashboard'
      preLoaderRoute: typeof DriverDashboardRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/achievements': {
      id: '/driver/achievements'
      path: '/achievements'
      fullPath: '/driver/achievements'
      preLoaderRoute: typeof DriverAchievementsRouteImport
      parentRoute: typeof DriverRoute
    }
    '/admin/pagamento': {
      id: '/admin/pagamento'
      path: '/pagamento'
      fullPath: '/admin/pagamento'
      preLoaderRoute: typeof AdminPagamentoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/entregas': {
      id: '/admin/entregas'
      path: '/entregas'
      fullPath: '/admin/entregas'
      preLoaderRoute: typeof AdminEntregasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/entregas/relatorios': {
      id: '/admin/entregas/relatorios'
      path: '/relatorios'
      fullPath: '/admin/entregas/relatorios'
      preLoaderRoute: typeof AdminEntregasRelatoriosRouteImport
      parentRoute: typeof AdminEntregasRoute
    }
    '/admin/entregas/pedidos': {
      id: '/admin/entregas/pedidos'
      path: '/pedidos'
      fullPath: '/admin/entregas/pedidos'
      preLoaderRoute: typeof AdminEntregasPedidosRouteImport
      parentRoute: typeof AdminEntregasRoute
    }
    '/admin/entregadores/mapa': {
      id: '/admin/entregadores/mapa'
      path: '/entregadores/mapa'
      fullPath: '/admin/entregadores/mapa'
      preLoaderRoute: typeof AdminEntregadoresMapaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/entregadores/acessos': {
      id: '/admin/entregadores/acessos'
      path: '/entregadores/acessos'
      fullPath: '/admin/entregadores/acessos'
      preLoaderRoute: typeof AdminEntregadoresAcessosRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminEntregasRouteChildren {
  AdminEntregasPedidosRoute: typeof AdminEntregasPedidosRoute
  AdminEntregasRelatoriosRoute: typeof AdminEntregasRelatoriosRoute
}

const AdminEntregasRouteChildren: AdminEntregasRouteChildren = {
  AdminEntregasPedidosRoute: AdminEntregasPedidosRoute,
  AdminEntregasRelatoriosRoute: AdminEntregasRelatoriosRoute,
}

const AdminEntregasRouteWithChildren = AdminEntregasRoute._addFileChildren(
  AdminEntregasRouteChildren,
)

interface AdminRouteChildren {
  AdminEntregasRoute: typeof AdminEntregasRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPagamentoRoute: typeof AdminPagamentoRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminEntregadoresAcessosRoute: typeof AdminEntregadoresAcessosRoute
  AdminEntregadoresMapaRoute: typeof AdminEntregadoresMapaRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminEntregasRoute: AdminEntregasRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AdminPagamentoRoute: AdminPagamentoRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminEntregadoresAcessosRoute: AdminEntregadoresAcessosRoute,
  AdminEntregadoresMapaRoute: AdminEntregadoresMapaRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DriverRouteChildren {
  DriverAchievementsRoute: typeof DriverAchievementsRoute
  DriverDashboardRoute: typeof DriverDashboardRoute
  DriverEarningsRoute: typeof DriverEarningsRoute
  DriverJornadaRoute: typeof DriverJornadaRoute
  DriverPerformanceRoute: typeof DriverPerformanceRoute
  DriverProfileRoute: typeof DriverProfileRoute
}

const DriverRouteChildren: DriverRouteChildren = {
  DriverAchievementsRoute: DriverAchievementsRoute,
  DriverDashboardRoute: DriverDashboardRoute,
  DriverEarningsRoute: DriverEarningsRoute,
  DriverJornadaRoute: DriverJornadaRoute,
  DriverPerformanceRoute: DriverPerformanceRoute,
  DriverProfileRoute: DriverProfileRoute,
}

const DriverRouteWithChildren =
  DriverRoute._addFileChildren(DriverRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CardapioRoute: CardapioRoute,
  CheckoutRoute: CheckoutRoute,
  DriverRoute: DriverRouteWithChildren,
  MeusPedidosRoute: MeusPedidosRoute,
  MinhaContaRoute: MinhaContaRoute,
  PedidoIdRoute: PedidoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
